language: objective-c
xcode_project: HelloWorld.xcodeproj
xcode_scheme: HelloWorld
osx_image: xcode8.2
script:
  - xcodebuild -scheme 'HelloWorld' -destination "platform=iOS Simulator,name=iPhone 6S"
